## ansible-playbook -i local.ini ./playbooks/hello_world.yml
- name: Simple playbook​
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Print hello world
    debug:
      msg: "Hello World!"
