## ansible-playbook -i inventories/local.ini ./playbooks/k8stest.yml
## prerequisite: need a configured k8s connection

- name: Playbook using k8s module
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Get info before
    k8s_info:
      api_version: v1
      kind: pod
      namespace: default
  - name: Create a Deployment by reading the definition from a local file
    k8s:
      state: present
      src: pod.yml
      namespace: default
  - name: Get info after
    k8s_info:
      api_version: v1
      kind: pod
      namespace: default
